---
name: CD

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build:
    name: Build Python package distributions
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"
          github-token: {% raw %}${{ secrets.GITHUB_TOKEN }}{% endraw %}

      - name: Build source distribution and wheel
        run: >-
          uv build
          --python-preference only-managed
          --python 3.13

      - name: Store Python package distributions
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/*

  publish-to-pypi:
    name: Publish to PyPI
    if: github.repository_owner == '{{ cookiecutter.github_owner }}' && github.event.action == 'published'
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/{{ cookiecutter.__project_slug }}

    permissions:
      id-token: write

    steps:
      - name: Download Python package distributions
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
