---
site_name: {{ cookiecutter.project_name }}
site_url: {{ cookiecutter.__github_pages }}
repo_url: {{ cookiecutter.__github_repository }}
repo_name: {{ cookiecutter.__github_slug }}
edit_uri: edit/main/docs/
site_description: "{{ cookiecutter.short_description }}"
site_author: {{ cookiecutter.author_name }}
copyright: Copyright &copy; {% now 'utc', '%Y' %} {{ cookiecutter.author_name }}

nav:
  - Home:
    - index.md
    - Changelog: changelog.md
  - API Reference:
    - api/index.md
    - api/{{ cookiecutter.__package_name }}.md
{%- if cookiecutter.cli %}
    - api/{{ cookiecutter.__package_name }}.__main__.md
    - api/{{ cookiecutter.__package_name }}.log.md
{%- endif %}

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

theme:
  name: material
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - navigation.indexes
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.suggest
    - toc.follow
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

site_dir: site

watch:
  - mkdocs.yaml
  - CHANGELOG.md
  - src/{{ cookiecutter.__package_name }}

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
      pygments_lang_class: true
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          inventories:
            - https://docs.python.org/3/objects.inv
          options:
            parameter_headings: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            inherited_members: true
            members_order: source
            summary: true
            docstring_style: google
            docstring_options:
              ignore_init_summary: true
            docstring_section_style: table
            merge_init_into_class: true
            show_signature_annotations: true
            separate_signature: true
            signature_crossrefs: true
