requires = [
  "tox>=4.23.2",
  "tox-uv>=1.25",
]
env_list = [
  "lint",
  "type",
  "type-tests",
  "docstrings",
  "pkg",
  "{{ cookiecutter.python_version }}",
  "coverage",
]
labels.checks = [
  "lint",
  "type",
  "type-tests",
  "docstrings",
  "pkg",
]
labels.tests = [
  "{{ cookiecutter.python_version }}",
  "coverage",
]

[env_run_base]
description = "Run tests under {env_name}"
package = "wheel"
wheel_build_env = ".pkg"
set_env = [
  { COVERAGE_PROCESS_START = "{tox_root}/pyproject.toml" },
]
dependency_groups = [ "tests" ]
commands_pre = [
  [
    "python",
    "-c",
    "'import pathlib; pathlib.Path(\"{env_site_packages_dir}/cov.pth\").write_text(\"import coverage; coverage.process_startup()\")'",
  ],
]
commands = [
  [ "coverage", "run", "-m", "pytest", { replace = "posargs", extend = true } ],
]

[env.coverage]
description = "Combine and check coverage"
depends = [
  "{{ cookiecutter.python_version }}",
]
skip_install = true
dependency_groups = [ "coverage" ]
commands = [
  [ "coverage", "combine" ],
  [ "coverage", "html" ],
  [ "coverage", "report" ],
]

[env.lint]
description = "Run all linters"
skip_install = true
pass_env = [
  "DISABLE_PRE_COMMIT_UV_PATCH",
]
set_env = [
  { FORCE_PRE_COMMIT_UV_PATCH = "1" },
]
dependency_groups = [ "lint" ]
commands = [
  [
    "pre-commit",
    "run",
    "--all-files",
    { replace = "posargs", extend = true },
  ],
]

[env.type]
description = "Type check Python packages"
base_python = [ "{{ cookiecutter.python_version }}" ]
dependency_groups = [ "type" ]
commands = [
  [ "mypy", "src" ],
]

[env.type-tests]
description = "Type check Python tests"
base_python = [ "{{ cookiecutter.python_version }}" ]
dependency_groups = [ "tests", "type" ]
commands = [
  [ "mypy", "tests" ],
]

[env.docstrings]
description = "Check docstring coverage"
skip_install = true
dependency_groups = [ "docstrings" ]
commands = [
  [
    "interrogate",
    "--verbose",
    { replace = "posargs", extend = true },
  ],
]

[env.pkg]
description = "Check the Python package"
skip_install = true
dependency_groups = [ "pkg" ]
commands = [
  [
    "uv",
    "build",
    "--out-dir",
    "{env_tmp_dir}",
  ],
  [
    "check-wheel-contents",
    "--no-config",
    "{env_tmp_dir}",
  ],
  [
    "twine",
    "check",
    "--strict",
    "{env_tmp_dir}{/}*",
  ],
]
{% if cookiecutter.docs %}
[env.docs]
description = "Generate documentation"
base_python = [ "{{ cookiecutter.python_version }}" ]
dependency_groups = [ "docs" ]
commands = [
  [
    "mkdocs",
    "build",
    "--clean",
    "--strict",
    { replace = "posargs", extend = true },
  ],
]

[env.autodocs]
description = "Serve documentation locally"
package = "editable"
base_python = [ "{{ cookiecutter.python_version }}" ]
dependency_groups = [ "docs" ]
commands = [
  [
    "mkdocs",
    "serve",
    "--strict",
    "--open",
    { replace = "posargs", extend = true },
  ],
]
{% endif %}
[env.release]
description = "Prepare a new release"
skip_install = true
dependency_groups = [ "release" ]
commands = [
  [
    "python",
    "{tox_root}{/}scripts{/}release.py",
    { replace = "posargs", extend = true },
  ],
]
